[metadata]
name = channel-checker
version = 0.1.5

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
install_requires =
    google-api-python-client
    google-auth-oauthlib
    playwright

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    channel-checker = channel_checker.__main__:main
